window.WAM_REFERENCE = {
  "voice-thu": {
    "id": "voice-thu",
    "title": "Voice & Movement • Thursday: Access as Arrival",
    "duration": "45 min",
    "lines": [
      "Thursday: Access as Arrival",
      "Cohort structure: 6 actors / 3 scene pairs",
      "Core question: What is available to me right now? The first session prioritizes awareness before correction. Actors are not asked to relax on command or manufacture openness. They observe the instrument they actually arrived with, then gently increase options.",
      "0:00-0:05 | Arrival and Orientation",
      "Purpose: Shift attention from logistics into embodied observation.",
      "Stand or sit comfortably. Notice contact with the floor or chair, temperature, breath rhythm, visual field, and where effort is already present.",
      "No one fixes anything yet. The task is information gathering.",
      "Facilitator prompts",
      "What is already available without you making anything happen?",
      "Where are you working harder than the moment requires?",
      "0:05-0:12 | Baseline Scan: Breath, Body, Attention",
      "Purpose: Establish a neutral reference point for later Pressure work.",
      "Scan jaw, tongue, shoulders, ribs, belly, hips, knees, hands, and feet.",
      "Notice where breath moves easily, where it pauses, and where attention tends to leave the room.",
      "Facilitator prompts",
      "Do not improve the breath. Observe it.",
      "What changes when you simply notice the room again?",
      "0:12-0:20 | Mobility and Release of Unnecessary Effort",
      "Purpose: Increase physical choices without chasing a specific posture.",
      "Mobilize head/neck, shoulders, spine, pelvis, knees, ankles, wrists, and hands through comfortable ranges.",
      "Alternate small movement with stillness so actors can feel the difference between support and gripping.",
      "Facilitator prompts",
      "What can move without the rest of you bracing?",
      "What can stay organized without becoming rigid?",
      "0:20-0:28 | Breath Into Sound",
      "Purpose: Connect breath to vibration and impulse rather than volume.",
      "Use easy hums, lip vibration, voiced sighs, and short open vowels.",
      "Let sound begin where breath already is. Do not push for resonance or loudness.",
      "Facilitator prompts",
      "Can the sound ride the breath instead of being placed on top of it?",
      "0:28-0:37 | Sound + Movement Range",
      "Purpose: Allow voice and body to influence one another.",
      "Walk the room and explore changes in direction, pace, weight, size, and stillness.",
      "Add simple sound or a neutral phrase. Let physical organization alter sound, then let sound alter physical organization.",
      "Keep the work exploratory rather than performative.",
      "Facilitator prompts",
      "What becomes more available when you change scale?",
      "What disappears when you start trying to be interesting?",
      "0:37-0:42 | Protection Pattern Snapshot",
      "Purpose: Create a bridge into Pressure in Action I.",
      "Ask actors to recall one moment today when they felt watched, rushed, uncertain, or exposed.",
      "Notice the body’s first protective response: bracing, shrinking, speeding up, smiling, going still, controlling breath, over-explaining, disconnecting, or another specific behavior.",
      "Facilitator prompts",
      "What does your instrument do when it decides it needs to protect you?",
      "0:42-0:45 | Close: Available, Not Perfect",
      "Purpose: Name one accessible resource before leaving the room.",
      "Each actor completes: “Right now I have access to…”",
      "Carry that awareness directly into the rest of Thursday.",
      "Sources & online resources",
      "The Linklater Center - Voice work centered on free, clear, strong vocal expression.",
      "The Complete Guide to the Alexander Technique - Background on reducing unnecessary effort and increasing psychophysical choice.",
      "Michael Chekhov Association - Practice-based psychophysical acting resources connecting body, imagination, and action."
    ]
  },
  "voice-fri": {
    "id": "voice-fri",
    "title": "Voice & Movement • Friday: Access as Expansion",
    "duration": "45 min",
    "lines": [
      "Friday: Access as Expansion",
      "Cohort structure: 6 actors / 3 scene pairs",
      "Core question: Can I widen the range of my instrument without forcing a result? Friday assumes the actors can notice baseline. The work now expands vocal, physical, and expressive options while preserving responsiveness.",
      "0:00-0:05 | Re-Arrival and Alignment Check",
      "Purpose: Reconnect to yesterday without trying to reproduce yesterday.",
      "Feet, floor, visual field, breath, jaw, shoulders, ribs, pelvis.",
      "Identify one place that feels open and one place doing extra work.",
      "0:05-0:13 | Release Pathway",
      "Purpose: Reduce interference in common effort zones.",
      "Gentle jaw release, tongue stretch, shoulder/upper-back mobility, ribs, hips, knees, and feet.",
      "Pair release with exhale or voiced sigh only when it helps rather than becoming a ritual.",
      "0:13-0:21 | Resonance and Articulation",
      "Purpose: Increase vocal access without equating access with loudness.",
      "Hum to vowel, easy resonance through lips/face/chest sensations, then short text.",
      "Articulation sequence prioritizes clarity with minimal jaw/tongue effort.",
      "Facilitator prompts",
      "Can the consonant be clear without becoming hard?",
      "Can the vowel stay alive without being pushed?",
      "0:21-0:31 | Vocal Range Lab",
      "Purpose: Expand pitch, pace, volume, texture, and silence as available choices.",
      "Speak the same neutral phrase across small changes in pitch, pace, volume, and texture.",
      "Do not “act” the variation. Notice what each adjustment does to thought, breath, and relationship.",
      "0:31-0:40 | Movement Range: Stillness to Full Expression",
      "Purpose: Increase scale while keeping choice specific.",
      "Move from minimal gesture to fuller spatial use and back to stillness.",
      "Add a line from the assigned scene only after the physical scale is clear.",
      "Preserve partner awareness even in larger movement.",
      "Facilitator prompts",
      "Can you become more expressive without becoming less specific?",
      "Can stillness remain active rather than dead?",
      "0:40-0:45 | Integration and Carryover",
      "Purpose: Choose one physical and one vocal access point for the day.",
      "Each actor names one resource they can return to if Pressure II or camera work narrows the instrument.",
      "Sources & online resources",
      "The Linklater Center - Voice training resources for freedom, clarity, strength, and expression.",
      "The Complete Guide to the Alexander Technique - Resources on coordination, tension, and efficient use.",
      "Michael Chekhov Association - Psychophysical training resources for imaginative and embodied range."
    ]
  },
  "voice-sat": {
    "id": "voice-sat",
    "title": "Voice & Movement • Saturday: Access Under Pressure",
    "duration": "45 min",
    "lines": [
      "Saturday: Access Under Pressure",
      "Cohort structure: 6 actors / 3 scene pairs",
      "Core question: Can I stay accessible when the room becomes demanding? Saturday is not about getting “more warmed up.” It trains recovery. The actor practices noticing when observation, direction, urgency, or technical demands narrow the instrument and returning without a dramatic reset.",
      "0:00-0:05 | Neutral to Readiness",
      "Purpose: Move quickly from arrival into usable readiness.",
      "Floor, breath, jaw, shoulders, spine, visual field.",
      "Three gentle full-body mobilizations, then stillness.",
      "0:05-0:12 | Breath Under Direction",
      "Purpose: Let external instruction change the task without seizing the breath.",
      "Walk or stand while receiving simple directions: slower, faster, smaller, turn, hold, restart, wait.",
      "Observe breath interruption and recover without “taking a calming breath” for show.",
      "Facilitator prompts",
      "Where did the instruction land in the body?",
      "Can you receive the note before solving it?",
      "0:12-0:20 | Recover Tension Without Leaving the Scene",
      "Purpose: Practice micro-resets.",
      "Cycle through brief effort states: rush, hold, wait, restart.",
      "Between rounds use a 5-10 second reset: see the room, feel the floor, complete the breath, release the prior round, find the partner.",
      "0:20-0:28 | Grounded Urgency",
      "Purpose: Separate urgency from rushing.",
      "Cross the room or deliver a short phrase with a concrete time need.",
      "Keep feet, breath, articulation, and partner contact available while pace increases.",
      "Facilitator prompts",
      "Can the need get stronger without the acting getting busier?",
      "0:28-0:36 | Expansion vs Camera Specificity",
      "Purpose: Practice changing scale without shrinking inner life.",
      "Take one scene line through full-room scale, conversational scale, then camera-close scale.",
      "Keep the same event, objective, and partner. Only the external scale changes.",
      "Facilitator prompts",
      "Smaller is not less. What stays fully alive when the external behavior gets economical?",
      "0:36-0:42 | Between-Take Reset",
      "Purpose: Prepare the instrument for Camera II and filming day.",
      "Practice stepping out of a take, releasing result, checking breath/body, and returning to the same objective and circumstances.",
      "Avoid recreating the prior emotional state.",
      "0:42-0:45 | Pre-Performance Need",
      "Purpose: Name the actor’s personal access cue.",
      "Each actor completes: “Before I work today, I need access to…” and chooses one practical cue rather than a mood.",
      "Sources & online resources",
      "SAG-AFTRA Foundation On-Camera Labs - Professional on-camera practice and taping resources.",
      "The Linklater Center - Voice freedom and expressive access.",
      "The Complete Guide to the Alexander Technique - Coordination and release of unnecessary effort under demand."
    ]
  },
  "voice-sun": {
    "id": "voice-sun",
    "title": "Voice & Movement • Sunday: Company Warm-Up",
    "duration": "30 min",
    "lines": [
      "Sunday: Company Warm-Up",
      "Cohort structure: Full acting company",
      "Core question: Can we arrive as one responsive company without flattening individual needs? This is the culmination of the prior three mornings. It should feel familiar, efficient, and confidence-building - not like a new class on filming day.",
      "0:00-0:03 | Arrive and Assess",
      "Purpose: Privately notice what the instrument needs today.",
      "Feet, floor, temperature, breath, jaw, shoulders, energy, attention.",
      "0:03-0:08 | Ground and Mobilize",
      "Purpose: Wake joints, spine, ribs, hips, knees, ankles, shoulders, wrists, neck.",
      "Keep the room quiet enough to register individual pace.",
      "0:08-0:12 | Release Unnecessary Effort",
      "Purpose: Clear gripping without chasing relaxation.",
      "Jaw/tongue, shoulders, hands, belly, knees. Easy sigh or hum if useful.",
      "0:12-0:17 | Connect Breath, Body, and Sound",
      "Purpose: Bring vibration into the moving body.",
      "Hum, lip vibration, vowels, gentle pitch travel, then one resonant phrase.",
      "0:17-0:21 | Articulation and Resonance",
      "Purpose: Wake precision for production audio.",
      "Short articulation sequence, then scene names/first lines at conversational volume.",
      "0:21-0:25 | Attention and Responsiveness",
      "Purpose: Turn the warm-up outward.",
      "In pairs: silent eye contact, small movement exchange, then one-word “Okay” response without preplanning.",
      "0:25-0:28 | Ensemble Synchronization",
      "Purpose: Share rhythm without forcing sameness.",
      "Company pulse: walk, stop, breathe, and begin again by collective attention rather than a counted cue.",
      "0:28-0:30 | Camera-Ready Focus",
      "Purpose: End with the work, not hype.",
      "See the room. Feel the floor. Complete the breath. Find the partner. Remember the objective.",
      "Final phrase together: “Receive. Reorganize. Respond.”",
      "Sources & online resources",
      "The Linklater Center - Voice access and expressive freedom.",
      "SAG-AFTRA Foundation On-Camera Labs - On-camera performance practice resources.",
      "Michael Chekhov Association - Psychophysical ensemble and imaginative training resources."
    ]
  },
  "pressure-1": {
    "id": "pressure-1",
    "title": "Pressure in Action I • Feel the Shift",
    "duration": "90 min",
    "lines": [
      "Pressure in Action I: Feel the Shift",
      "Cohort structure: 6 actors / 3 scene pairs",
      "Central question: What changes in me when the conditions change? Experience comes before vocabulary. Actors first encounter changing conditions, observe their body and protective behavior, and only then name the Pressure fields.",
      "0:00-0:08 | Frame the Work",
      "Purpose: Define Pressure as changed conditions, not performed intensity.",
      "Introduce the working definition: Pressure is a change in the conditions surrounding what I want.",
      "Explain that Pressure may alter timing, breath, attention, access, risk, need, or behavior.",
      "The first response is information. The actor is not trying to “look affected.”",
      "Facilitator prompts",
      "Something changes. What does your organism do before you decide what it should do?",
      "0:08-0:18 | Establish the Baseline",
      "Purpose: Give the actor something to compare change against.",
      "Standing baseline: breath, body, visual attention, pace, muscular effort.",
      "Write three neutral observations on the Pressure Pathway Card.",
      "Teach Return to Now and practice it twice.",
      "Facilitator prompts",
      "What is true before anything changes?",
      "0:18-0:42 | The Evolving Task Laboratory",
      "Purpose: Let actors experience Pressure before naming fields.",
      "Work in three pairs. One actor performs a simple repeatable task while the partner administers the changing condition.",
      "Base task: move three objects to a chair in a specific order.",
      "Round 1 - Basic: complete the task with no added condition.",
      "Round 2 - Time: complete it in 10 seconds.",
      "Round 3 - Access: the partner holds the final object; the actor must get access rather than grab it.",
      "Round 4 - Knowledge/Control: the order changes; the partner knows the new order and answers only direct questions.",
      "After each round: Return to Now, then answer the three shared questions.",
      "Facilitator prompts",
      "What changed?",
      "What did that change in your breath, attention, timing, or impulse?",
      "What did you do next?",
      "0:42-0:55 | Discover the Protection Pattern",
      "Purpose: Separate protection from failure.",
      "Each actor completes: “When pressure changes, I tend to protect myself by…”",
      "Make the answer behavioral and specific: speed up, smile, freeze, over-explain, control, withdraw, go vague, get louder, stop breathing, etc.",
      "Identify when protection reduces availability to partner, task, or circumstances.",
      "Add to card: protection pattern, how it makes me unavailable, one way back.",
      "Facilitator prompts",
      "Protection is not bad acting. It is useful information. Does the protection still serve the scene?",
      "0:55-1:13 | Carry the Process Into the Scene",
      "Purpose: Transfer body awareness into the assigned WAM material.",
      "Each pair uses the same 60-90 second scene passage that will return in Workshops II and III.",
      "Run the passage once without interruption.",
      "Choose one moment where an observable condition changes. Do not map the entire scene yet.",
      "Replay only the short section around that change. Actor identifies event → body signal → protective impulse → next behavior.",
      "Use Return to Now before each replay.",
      "Facilitator prompts",
      "What happened outside of you?",
      "Where did you register it?",
      "What did your protection want to do?",
      "What became necessary next?",
      "1:13-1:22 | Name the Five Fields",
      "Purpose: Attach language to lived experience.",
      "Reveal the five WAM Pressure fields: Control, Access, Time, Knowledge, Loyalty.",
      "Return to examples from the task and scenes. Let actors name which field best describes what shifted.",
      "Allow overlap; the purpose is diagnosis, not forcing every event into one box.",
      "Facilitator prompts",
      "Which field helps you describe the condition that changed?",
      "1:22-1:30 | Consolidation and Reset",
      "Purpose: Leave actors with a repeatable awareness process.",
      "Pressure Pathway Card now holds: baseline, changed condition, body signal, protection pattern, availability problem, return cue, possible field.",
      "Final Return to Now.",
      "Bridge to Listening I: your partner will now become the primary source of changing conditions.",
      "Internal source update: current source terminology is The Adaptive Breath Cycle (2026). Earlier WAM lesson-plan drafts used a prior working title.",
      "Sources & online resources",
      "Michael Chekhov Association - Psychophysical acting resources connecting inner event and physical action.",
      "The Complete Guide to the Alexander Technique - Background on awareness, habit, and release of unnecessary effort."
    ]
  },
  "pressure-2": {
    "id": "pressure-2",
    "title": "Pressure in Action II • Use the Shift",
    "duration": "90 min",
    "lines": [
      "Pressure in Action II: Use the Shift",
      "Cohort structure: 6 actors / 3 scene pairs",
      "Central question: Once I notice the shift, how does it change what I do to get what I want? Workshop II moves from awareness into organized pursuit. Objective stays stable long enough to be playable; tactics change as conditions and partner behavior change.",
      "0:00-0:08 | Recover Workshop I",
      "Purpose: Reactivate the process rather than reteach the theory.",
      "Three shared questions out loud.",
      "Quick Return to Now.",
      "Actors review yesterday’s Pressure Pathway Card and identify their common protection pattern.",
      "0:08-0:20 | Discovery Run",
      "Purpose: Let the scene reveal what the actor is already pursuing.",
      "Three pairs run the same 60-90 second passage once.",
      "Observers track only: what does each person seem to be trying to change in the other person? No notes on emotion or “choices.”",
      "0:20-0:34 | Discover and Name the Objective",
      "Purpose: Make pursuit concrete and relational.",
      "Use WAM objective format: “I want to ___ you so you will ___.”",
      "Test the objective against the scene: can the partner actually do the second half? Does it create behavior rather than mood?",
      "Each actor states one objective. Keep it playable and specific.",
      "Facilitator prompts",
      "What are you trying to get from this person, not from the scene?",
      "If you got it, what would they actually do?",
      "0:34-0:45 | Second Run: Pursue the Objective",
      "Purpose: Feel the difference between intention and result-playing.",
      "Pairs rerun the passage with the objective active.",
      "Do not plan tactics. Let the first behavior emerge from pursuit.",
      "Stop only if the objective disappears into generalized emotion.",
      "0:45-0:58 | Discover the Shift and Separate Protection",
      "Purpose: Identify when the original way of pursuing stops working.",
      "Locate one pressure shift in each pair’s passage.",
      "Name what changed in conditions and which field is most useful: Control, Access, Time, Knowledge, Loyalty.",
      "Identify the protective impulse separately from the responsive action. Protection may be useful, but it should not automatically become the tactic.",
      "Facilitator prompts",
      "What just changed?",
      "What did it make harder, riskier, less available, or more urgent?",
      "What did your body want to do to protect you?",
      "0:58-1:12 | The Shift Laboratory",
      "Purpose: Train adaptation without turning tactics into line readings.",
      "Work the same 4-8 lines around the shift three times.",
      "Round A: let the shift land; do not fix anything.",
      "Round B: keep the objective and allow the tactic to change only when the partner’s behavior requires it.",
      "Round C: partner changes one truthful piece of behavior so the actor cannot reproduce the previous solution.",
      "Return to Now between rounds.",
      "Facilitator prompts",
      "What are you doing now because the old way stopped working?",
      "Did your tactic change your partner? If not, what does that require of you?",
      "1:12-1:25 | Full Pressure Pathway Run",
      "Purpose: Integrate objective, pressure, protection, and adaptation.",
      "Each pair runs the full passage.",
      "Actor sequence: Calibrate → Anchor Objective → Notice Pressure → Stay Available → Respond → Reset only after the run.",
      "Observers track one earned shift and one moment where the actor adapted instead of repeating a plan.",
      "1:25-1:30 | Complete the Pressure Pathway",
      "Purpose: Prepare the card for Workshop III.",
      "Add: objective, key pressure shift, field, first protection impulse, tactic before shift, tactic after shift, and Return to Now cue.",
      "Bridge to camera: tomorrow the process must survive observation, technical constraints, direction, and repeated takes.",
      "Internal source update: current source terminology is The Adaptive Breath Cycle (2026). Earlier WAM lesson-plan drafts used a prior working title.",
      "Sources & online resources",
      "The Neighborhood Playhouse - Professional Meisner-based actor training emphasizing truthful, disciplined performance and partner-centered work.",
      "NYU Tisch - The Meisner Studio - Conservatory context for integrated acting, movement, voice, and speech training."
    ]
  },
  "pressure-3": {
    "id": "pressure-3",
    "title": "Pressure in Action III • Repeat the Process",
    "duration": "90 min",
    "lines": [
      "Pressure in Action III: Repeat the Process",
      "Cohort structure: 6 actors / 3 scene pairs",
      "Central question: Can I repeat the process without repeating the result? The actor now has to preserve story truth while managing room pressure: observation, time, camera, marks, continuity, a director’s note, and the temptation to recreate a previous take.",
      "0:00-0:08 | Recover the Pathway",
      "Purpose: Put the entire process back in the body.",
      "Review Pressure Pathway Card.",
      "Return to Now.",
      "State objective, key shift, strongest field, protection pattern, and reset cue in one minute per pair.",
      "0:08-0:15 | Build the Repeatable Pathway",
      "Purpose: Choose what should be repeatable and what must remain alive.",
      "Repeatable: circumstances, objective, required blocking/mark, key story event, practical continuity.",
      "Not fixed: exact feeling, exact breath, exact rhythm, exact tactic if the partner gives something different.",
      "0:15-0:39 | Take One: The Prepared Pathway",
      "Purpose: Establish a truthful baseline take.",
      "Three pairs perform the same scene passage under simple camera/observer conditions.",
      "No performance note before the take. Actors use the pathway they already built.",
      "Immediate note after each pair: where did the process stay alive? where did performance become reproduced?",
      "0:39-0:50 | Name Story Pressure and Room Pressure",
      "Purpose: Teach actors to distinguish fictional conditions from production conditions.",
      "Story Pressure: what changes inside the scene and affects the character’s pursuit.",
      "Room Pressure: camera position, being watched, time, mark, continuity, crew movement, note, restart, technical delay.",
      "Room Pressure is real for the actor but should not replace the character’s circumstances.",
      "Facilitator prompts",
      "What pressure belongs to the story?",
      "What pressure belongs to the room?",
      "What do you need to acknowledge and then stop feeding?",
      "0:50-0:58 | Receive and Translate Direction",
      "Purpose: Practice taking a note without abandoning the existing work.",
      "Give each pair one concise adjustment: pace, withholding, proximity, eyeline, physical economy, urgency, or relational emphasis.",
      "Actor repeats the note back in plain language, identifies what part of the process it affects, and does not pre-perform the solution.",
      "Facilitator prompts",
      "What does the note change in the conditions or pursuit?",
      "What stays the same?",
      "0:58-1:20 | Take Two: Repeat the Process",
      "Purpose: Apply direction while preserving responsiveness.",
      "Pairs run again with the adjustment and one practical production condition such as a mark, limited movement, reset position, or changed camera proximity.",
      "Return to Now before each take.",
      "Observers look for repeatability of story and openness to new partner behavior.",
      "1:20-1:27 | Playback / Process Comparison",
      "Purpose: Compare process, not “which take was better.”",
      "Watch short moments from Take One and Take Two where available.",
      "Actors identify: what was repeatable, what changed honestly, where room pressure hijacked attention, and where they stayed available.",
      "1:27-1:30 | Final Integration and Reset",
      "Purpose: Convert the pathway into a filming-day card.",
      "Final card: objective; strongest Pressure field; when pressure worsens; can’t-miss story event; what the character cannot afford to reveal; first playable action; protection pattern; Return to Now cue.",
      "Final reset. The next work is Camera II, where technical machinery becomes more explicit.",
      "Internal source update: current source terminology is The Adaptive Breath Cycle (2026). Earlier WAM lesson-plan drafts used a prior working title.",
      "Sources & online resources",
      "SAG-AFTRA Foundation On-Camera Labs - Professional resources for camera performance and self-taping practice.",
      "The Neighborhood Playhouse - Two-Year Conservatory - Includes acting for film/television, responsiveness to direction, and disciplined screen performance."
    ]
  },
  "listening-1": {
    "id": "listening-1",
    "title": "Listening & Responding I • Receive Before You Respond",
    "duration": "90 min",
    "lines": [
      "Listening & Responding I: Receive Before You Respond",
      "Cohort structure: 6 actors / 3 scene pairs",
      "0:00-0:10 | Re-Entry: Reactivate Pressure I",
      "Purpose: Connect partner work to the body/protection discoveries already made.",
      "Circle check-in: one protection pattern noticed in Pressure I.",
      "Return to Now.",
      "State the relational version: “What happened? → What did it do to me? → What do I do now?”",
      "Facilitator prompts",
      "Earlier, we looked at what your body does when pressure enters. What did you notice about the way you protect yourself?",
      "0:10-0:25 | Baseline: See the Person",
      "Purpose: Make the partner the task.",
      "In three pairs, face one another without text for short 30-45 second rounds.",
      "Notice actual behavior: breath, gaze, movement, hesitation, smile, avoidance, change in distance.",
      "No interpretation aloud until the round is over.",
      "Facilitator prompts",
      "Can you look at the person without searching for something to react to?",
      "What actually changed, not what did you imagine changed?",
      "0:25-0:45 | One-Word “Okay”",
      "Purpose: Strip away text so receiving becomes unavoidable.",
      "One actor gives a simple thought/circumstance or behavior; the receiving actor answers only “Okay.”",
      "The receiver waits until something lands before speaking. No designed line reading.",
      "Switch repeatedly. Keep rounds short enough that the actor cannot settle into a performance pattern.",
      "Facilitator prompts",
      "Do not show us that it landed. Let it land.",
      "Where did the word come from after you received them?",
      "0:45-1:02 | The Change Exercise",
      "Purpose: Train the actor to detect the exact moment the partner becomes different.",
      "Pairs converse using a neutral task or simple improvised exchange.",
      "Whenever the observer or teacher sees a real behavioral change, call “change.”",
      "Both actors freeze for one breath and identify only the observable change. Then continue from the new condition.",
      "Avoid emotional labels unless they arise after the behavior is clear.",
      "Facilitator prompts",
      "What changed between you?",
      "What became different in the room after that happened?",
      "1:02-1:17 | Silent Pressure Exchange",
      "Purpose: Receive relational pressure without text as a shield.",
      "One actor needs a simple nonverbal outcome from the partner: closer/farther, attention/space, stay/leave the chair, hand over/keep an object.",
      "No speech. The receiving actor lets the other person’s behavior alter breath, timing, and next action.",
      "Switch roles and repeat.",
      "Facilitator prompts",
      "When did you stop receiving and start planning?",
      "What did silence make you want to do?",
      "1:17-1:27 | Assigned Scene-Partner Transfer",
      "Purpose: Move the listening sequence into the actual WAM relationship.",
      "Stay with established scene partners.",
      "Each actor completes the three prompts before running 4-8 lines of the scene.",
      "Run once with the only instruction: receive before answering.",
      "Facilitator prompts",
      "In this scene, I need you to…",
      "The possibility that you will not give me that creates pressure because…",
      "When you withdraw, resist, misunderstand, or surprise me, I tend to…",
      "1:27-1:30 | Exit",
      "Purpose: Make one behavioral commitment for rehearsal.",
      "Each actor answers: “What do you need to stop doing so that your partner can affect you?”",
      "Internal source update: current source terminology is The Adaptive Breath Cycle (2026). Earlier WAM lesson-plan drafts used a prior working title.",
      "Sources & online resources",
      "The Neighborhood Playhouse - Home of the conservatory tradition associated with Sanford Meisner and partner-centered, truthful acting training.",
      "NYU Tisch - The Meisner Studio - Integrated Meisner-based conservatory training in acting, voice, speech, and movement."
    ]
  },
  "listening-2": {
    "id": "listening-2",
    "title": "Listening & Responding II • Affect and Be Affected",
    "duration": "90 min",
    "lines": [
      "Listening & Responding II: Affect and Be Affected",
      "Cohort structure: 6 actors / 3 scene pairs",
      "0:00-0:08 | Reactivate the Shared Language",
      "Purpose: Combine yesterday’s listening loop with active pursuit.",
      "Actors repeat: Receive → Register → Respond.",
      "Add: Pursue → Assess → Adjust.",
      "Write the full loop: Pursue → Receive → Register → Adjust → Continue.",
      "Clarify: pursuit is not pushing; adjustment is not a mental restart.",
      "0:08-0:20 | Working on the Other Person",
      "Purpose: Give pursuit a simple behavioral target.",
      "In three pairs, Actor A has one concrete goal that requires Actor B to change behavior: sit, stay, look at me, give me the object, move closer, stop talking, etc.",
      "Actor A may speak naturally but cannot explain the exercise. Actor B responds truthfully rather than helping.",
      "Switch after several short attempts.",
      "Facilitator prompts",
      "Did what you just did change your partner?",
      "If not, what does that require of you now?",
      "0:20-0:36 | One Want, Many Ways",
      "Purpose: Discover tactics as behavior, not vocabulary.",
      "Keep the same objective for the whole round.",
      "When a behavior stops affecting the partner, the actor must let the partner’s response generate the next attempt.",
      "After the round, name the behaviors that emerged: charm, reason, challenge, soften, withdraw, confront, tease, plead, redirect, etc. Naming comes after doing.",
      "0:36-0:52 | Resistance Without Pushing",
      "Purpose: Keep objective alive when the partner does not cooperate.",
      "Give the partner an incompatible need or boundary.",
      "Pursuer may not simply get louder, faster, or repeat the same tactic three times.",
      "If the actor begins forcing, pause and ask what the partner actually did that should change the pursuit.",
      "Facilitator prompts",
      "Are you pursuing them, or pursuing your plan?",
      "What new information did their resistance give you?",
      "0:52-1:07 | Interruption, Silence, Delay",
      "Purpose: Train availability when timing becomes relational.",
      "Repeat short rounds where the partner interrupts, waits longer than expected, answers indirectly, or goes silent.",
      "The actor cannot fill the silence automatically. They must receive the timing change as information.",
      "Switch who carries the timing disruption.",
      "Facilitator prompts",
      "What did the delay do to the pressure?",
      "What did you start doing because silence scared you?",
      "1:07-1:24 | Scene Pair Lab",
      "Purpose: Integrate active pursuit into the actual WAM scene.",
      "Three established pairs use the same 60-90 second passage.",
      "Before running: each actor states objective in one sentence.",
      "Run with full loop active. Teacher side-coaches only when the actor repeats a dead tactic or stops receiving.",
      "If needed, rerun the short shift area rather than restarting the full scene.",
      "Facilitator prompts",
      "Pursue. Receive what came back. Register. Adjust. Continue.",
      "1:24-1:30 | Close: Active Exchange",
      "Purpose: Name what changed because the partner was allowed to matter.",
      "Each actor identifies one moment where their partner changed the tactic and one moment where they changed the partner.",
      "Final phrase: “I affect you. You affect me. What you do changes how I continue trying to affect you.”",
      "Sources & online resources",
      "The Neighborhood Playhouse - Meisner-based actor training and the reality of partner-centered doing.",
      "NYU Tisch - The Meisner Studio - Conservatory context for truthful, relational acting practice."
    ]
  },
  "camera-1": {
    "id": "camera-1",
    "title": "Acting for the Camera I • The Camera Sees the Thought",
    "duration": "90 min",
    "lines": [
      "Acting for the Camera I: The Camera Sees the Thought",
      "Cohort structure: 6 actors / 3 scene pairs",
      "0:00-0:08 | Arrival: The Camera Is Listening",
      "Purpose: Reconnect Pressure II to screen behavior.",
      "Ask actors what happens when they become aware that a camera is watching.",
      "Identify common protection: presenting, tightening, shrinking everything, fixing the face, anticipating lines, trying to look natural.",
      "Set the goal: camera-readable thought without demonstrated feeling.",
      "Facilitator prompts",
      "Where do you start performing for the audience instead of receiving the scene?",
      "0:08-0:18 | Bailen Orientation: What the Director/DP Needs",
      "Purpose: Demystify the technical relationship so actors can stop spending attention on it.",
      "Bailen explains frame size, coverage, basic eyeline logic, marks, continuity, reset, and why multiple takes exist.",
      "Emphasize that technical precision supports storytelling; it is not a separate performance.",
      "Darius connects each demand to availability: acknowledge it, then return attention to circumstances and partner.",
      "0:18-0:35 | Hit Before the Line",
      "Purpose: Train the camera to catch the event before speech.",
      "Split six actors into two groups of three: actor, partner/reader, observer. Rotate roles.",
      "Frame actor in medium close-up where possible.",
      "Partner gives a simple piece of information or behavior. Actor receives it, lets it register, then speaks one neutral line such as “Okay.”",
      "Observer identifies the first moment they could see the thought land and the moment, if any, the actor began presenting the response.",
      "Repeat with less preparation, not less inner life.",
      "Facilitator prompts",
      "Do not show me the feeling. Let me catch you having it.",
      "What happened before the line?",
      "0:35-0:45 | The Camera’s Three States",
      "Purpose: Differentiate indicating, suppressing, and receiving.",
      "Demonstrate the same beat three ways: indicating the feeling, suppressing all response, and truthfully receiving while external behavior stays economical.",
      "Actors try each state briefly so the distinction is experiential.",
      "Name active stillness: little movement does not mean little happening.",
      "0:45-1:15 | Scene Excerpt Lab",
      "Purpose: Apply camera availability to the WAM scene.",
      "Each pair uses a 45-60 second excerpt containing one clear pressure/new-information event.",
      "Per pair: prepared run → very brief playback/diagnosis → second run with one availability adjustment.",
      "Adjustment is not “do less.” It may be: receive before answering, stop protecting silence, keep the objective active, let the thought change before the tactic changes.",
      "Keep playback diagnostic: what is visible, when did the actor start performing, what can be removed without removing the event?",
      "Facilitator prompts",
      "Do not protect the scene from silence.",
      "Where did the pressure land?",
      "Where did the thought change?",
      "What can we remove?",
      "1:15-1:25 | Director’s Eye",
      "Purpose: Let Bailen identify what is already communicating.",
      "For each pair, Bailen names one specific moment the camera could read clearly and one place where the actor can trust the frame more.",
      "Where useful, connect note to framing, eyeline, or physical economy rather than giving a line reading.",
      "Facilitator prompts",
      "What are you protecting?",
      "Where does the thought change?",
      "What can we remove without losing the event?",
      "1:25-1:30 | Personal Camera Anchor",
      "Purpose: Give each actor one private cue to carry into future takes.",
      "Each actor completes: “When I become aware of the camera, I will…”",
      "Then choose one camera anchor: partner, objective, first new piece of information, physical task, or pre-scene knowledge.",
      "Facilitator prompts",
      "Before the scene begins, what do you want the camera to catch you already knowing?",
      "Sources & online resources",
      "SAG-AFTRA Foundation On-Camera Labs - Professional on-camera rehearsal and taping resources.",
      "The Neighborhood Playhouse - Acting for Film & Television - Professional actor training that includes filmed/reviewed work and responsiveness to direction.",
      "SAG-AFTRA Foundation Conversations - Recorded performer/director conversations with practical career and craft insight."
    ]
  },
  "camera-2": {
    "id": "camera-2",
    "title": "Acting for the Camera II • Stay Alive Inside the Machinery",
    "duration": "90 min",
    "lines": [
      "Acting for the Camera II: Stay Alive Inside the Machinery",
      "Cohort structure: 6 actors / 3 scene pairs",
      "0:00-0:10 | Camera I Reactivation With a Mark",
      "Purpose: Reconnect truthful receiving to technical placement.",
      "Each actor crosses to a simple mark, settles, receives one partner cue, and speaks a line.",
      "Repeat. Goal: land accurately without looking down, bracing, or arriving mentally before the body.",
      "Darius side-coaches partner/objective; Bailen corrects only the necessary technical behavior.",
      "0:10-0:22 | Bailen: Set Workflow in Plain Language",
      "Purpose: Map the actor’s real job inside production.",
      "Walk through: rehearsal/blocking → marks → camera/lighting adjustment → take → cut → reset → note → repeat → coverage.",
      "Explain why eyelines, frame, continuity, sound, and camera position may change while the story event must remain coherent.",
      "Actors can ask concise practical questions; avoid turning this into a gear lecture.",
      "0:22-0:32 | Continuity Demo",
      "Purpose: Separate continuity of behavior from duplication of emotion.",
      "Darius/Bailen demonstrate a short physical action with a prop or gesture across two takes.",
      "Class identifies what production may need repeated: hand, prop, position, timing relative to line, eyeline, entrance/exit.",
      "Then identify what may honestly vary: breath, thought timing, degree of feeling, tactic response to partner.",
      "Facilitator prompts",
      "What must match for the edit?",
      "What must stay alive for the performance?",
      "0:32-1:14 | Director’s Adjustment Lab",
      "Purpose: Give every scene pair repeated takes under practical and performance notes.",
      "Approximately 14 minutes per pair.",
      "Take 1: run 45-60 second excerpt as prepared.",
      "Bailen gives one technical condition: mark, eyeline, smaller frame, limited movement, reset position, prop continuity, or changed coverage.",
      "Darius gives or translates one acting adjustment only if needed: objective clarity, receive the new information, protect less, pursue differently, stay with partner.",
      "Take 2: actor applies both without reproducing Take 1.",
      "Optional quick Take 3 on 2-4 lines if the adjustment needs another repetition.",
      "Keep notes brief enough that actors actually practice receiving direction rather than discussing it.",
      "Facilitator prompts",
      "What stayed alive when the machinery changed?",
      "Where did the technical note steal your attention?",
      "Can you keep the relationship while obeying the frame?",
      "1:14-1:24 | Taking Direction Without Rebuilding the Scene",
      "Purpose: Train rapid note translation.",
      "All six actors stand ready with one short line or beat.",
      "Bailen gives each actor a concise adjustment. Actor answers with what they understand the practical task to be, then immediately tries it.",
      "No apology, explanation, or long intellectual processing.",
      "After the attempt: keep, clarify, or release the note.",
      "Facilitator prompts",
      "Receive the note. Translate it. Try it. Stay available.",
      "1:24-1:30 | Filming-Day Contract",
      "Purpose: Set practical actor behavior for Sunday.",
      "Each actor commits to: know the objective and pathway; hit marks without sacrificing partner; protect continuity; listen to direction; reset without chasing prior feeling; ask concise questions; stay ready between takes.",
      "Final company reminder: the set can be busy while the scene stays simple.",
      "Sources & online resources",
      "SAG-AFTRA Foundation On-Camera Labs - Professional camera practice and audition-taping resources.",
      "The Neighborhood Playhouse - Acting for Film & Television - Filmed/reviewed scene training and responsiveness to direction.",
      "SAG-AFTRA Foundation Conversations - Long-form craft conversations with working performers and industry professionals."
    ]
  },
  "rehearse": {
    "id": "rehearse",
    "title": "Rehearse Like a Pro",
    "duration": "30 min",
    "lines": [
      "Rehearse Like a Pro",
      "Cohort structure: 6 actors / 3 scene pairs",
      "0:00-0:05 | What Rehearsal Is For",
      "Purpose: Replace “practice the performance” with investigation and repeatable process.",
      "Rehearsal is where actors clarify circumstances, relationship, objective, shifts, blocking, and practical problems.",
      "Rehearsal is not where actors agree on exact line readings or lock emotional results.",
      "Professional rule: do not direct your partner’s feelings. Communicate what you need from the relationship or staging.",
      "0:05-0:10 | First Pass: Discover, Don’t Correct",
      "Purpose: Teach the first-run rule.",
      "Run the selected passage without stopping unless there is a safety or text problem.",
      "After the run, each actor names one thing that actually happened and one question - not five notes.",
      "Do not fix moments that have only happened once.",
      "0:10-0:15 | Two-Minute Partner Check",
      "Purpose: Keep rehearsal conversation playable.",
      "Each pair answers: What do I want from you? What is making it hard? Where does something clearly change? What practical staging must be agreed?",
      "Resolve only facts and logistics that genuinely need agreement.",
      "0:15-0:20 | One Variable at a Time",
      "Purpose: Prevent note overload and dead repetition.",
      "Choose one 4-12 line section and one question to test.",
      "Examples: does the objective hold? did the pressure shift land? am I receiving before responding? can this blocking work without losing connection?",
      "Rerun only that section. Compare what changed.",
      "0:20-0:25 | Useful Notes and Actor Language",
      "Purpose: Make notes behavioral and actionable.",
      "Prefer: “I lost you after the interruption,” “I need more space here,” “When you looked away I started pushing,” “Can we try staying farther apart?”",
      "Avoid: “Be angrier,” “say it like this,” “you should feel betrayed,” or diagnosing the partner.",
      "Write discoveries. Do not keep them all in memory.",
      "0:25-0:30 | Rehearsal Contract + Handoff",
      "Purpose: Launch directly into the first 90-minute rehearsal.",
      "Phones away except for script/reference use. Respect the partner’s boundaries and time.",
      "Work in chunks. Use Return to Now between repeated attempts.",
      "End every rehearsal with one full run, one or two retained discoveries, and one unanswered question for the next session.",
      "Do not rehearse until nothing can surprise you.",
      "Sources & online resources",
      "SAG-AFTRA Foundation Conversations - Working-actor and filmmaker discussions that can support professional rehearsal/set expectations.",
      "The Neighborhood Playhouse - Two-Year Conservatory - Professional conservatory training integrating scene work, interpretation, camera, and disciplined practice."
    ]
  },
  "guest-1": {
    "id": "guest-1",
    "title": "Guest Workshop #1 • Operational Brief",
    "duration": "90 min",
    "lines": [
      "Guest Workshop #1",
      "Cohort structure: 6 actors",
      "Darius opens with a 2-3 minute context statement connecting the guest’s work to the day without forcing WAM terminology onto the guest.",
      "Guest receives the full 90 minutes minus the agreed opening/close.",
      "Darius observes and takes integration notes rather than co-teaching unless invited.",
      "Final 5 minutes: each actor records one tool, question, or discovery they will carry into the rest of WAM.",
      "Any exercise involving touch, intimacy, high physical demand, or emotionally intense personal disclosure requires explicit opt-in and a clear alternative."
    ]
  },
  "guest-2": {
    "id": "guest-2",
    "title": "Guest Workshop #2 • Operational Brief",
    "duration": "90 min",
    "lines": [
      "Guest Workshop #2",
      "Cohort structure: 6 actors",
      "Same operational container as Guest Workshop #1.",
      "Because Pressure III follows, avoid using the final minutes to overload actors with new terminology they must immediately retain.",
      "Darius closes by asking what is usable today, then resets the room before Pressure III begins.",
      "The guest session remains a distinct perspective; integration means carrying useful discoveries forward, not translating every guest idea into Pressure Dynamics."
    ]
  },
  "safeguards": {
    "id": "safeguards",
    "title": "Master Teaching Safeguards",
    "duration": "Reference",
    "lines": [
      "Master Teaching Safeguards",
      "Experience before vocabulary. Let actors encounter the event first. Name the Pressure field, tactic, protection pattern, or camera principle after there is behavior to describe.",
      "No forced emotion. Do not prescribe a feeling or visible breath pattern. Changed circumstances and relationship create the conditions; emotion may emerge.",
      "Breath is evidence, not decoration. A breath change may reveal reorganization, but actors should not perform a breath to prove they were affected.",
      "Protection is information. Bracing, shrinking, controlling, rushing, joking, withdrawing, or over-explaining are not automatically errors. Ask whether the behavior keeps the actor available and serves the circumstances.",
      "One adjustment at a time. Especially in camera and rehearsal work, stack fewer notes and give the actor enough repetition to embody the adjustment.",
      "Do not rehearse the life out of the work. Repeat structure, conditions, blocking, objective, and technical continuity. Leave exact emotional results alive.",
      "Separate story pressure from room pressure. Actors can acknowledge being watched, timed, framed, or redirected without feeding those real-world pressures into the character unless useful.",
      "Agency and opt-out. Actors may pause or choose a lower-intensity version of an exercise. Truthful work is not dependent on emotional flooding or personal disclosure.",
      "Reinforce, do not restart. Each class should reactivate prior tools in minutes, then deepen them. WAM should feel like one curriculum becoming more demanding, not a series of unrelated workshops.",
      "Resource Bibliography",
      "The Linklater Center - Voice and speech resources grounded in the Linklater tradition.",
      "The Complete Guide to the Alexander Technique - General Alexander Technique resource hub.",
      "Michael Chekhov Association (MICHA) - Practice-based resources on Michael Chekhov Technique.",
      "National Michael Chekhov Association - Additional Michael Chekhov training resources.",
      "The Neighborhood Playhouse School of the Theatre - Professional conservatory training rooted in the Meisner tradition.",
      "NYU Tisch - The Meisner Studio - University conservatory context for Meisner-based acting training.",
      "SAG-AFTRA Foundation On-Camera Labs - Professional on-camera taping and rehearsal resources for members.",
      "SAG-AFTRA Foundation Conversations - Recorded career and craft conversations with performers and filmmakers.",
      "Internal source update: current source terminology is The Adaptive Breath Cycle (2026). Earlier WAM lesson-plan drafts used a prior working title."
    ]
  }
};
